# Generated by Django 4.2.7 on 2023-11-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompressedPDF',
        ),
    ]
